const Types = {
  AUTH_LOADING: 'AUTH_LOADING',
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SIGN_ERROR: 'SIGN_ERROR',
  SIGN_OUT: 'SIGN_OUT',

  PRODUCT_LOADING: 'PRODUCT_LOADING',
  PRODUCT_SEARCH: 'PRODUCT_SEARCH',
  PRODUCT_LIST: 'PRODUCT_LIST',

  CATEGORY_LOADING: 'CATEGORY_LOADING',
  CATEGORY_LIST: 'CATEGORY_LIST',
  CATEGORY_PRODUCTS: 'CATEGORY_PRODUCTS'
};
export default Types;
