const Types = {
  AUTH_LOADING: 'AUTH_LOADING',
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SIGN_ERROR: 'SIGN_ERROR',
  SIGN_OUT: 'SIGN_OUT',

  PRODUCT_LOADING: 'PRODUCT_LOADING',
  PRODUCT_SEARCH: 'PRODUCT_SEARCH',
  PRODUCT_LIST: 'PRODUCT_LIST',
  PRODUCT_ID: 'PRODUCT_ID',
  
  CLIENT_LOADING: 'CLIENT_LOADING',
  CLIENT_LIKES: 'CLIENT_LIKES',
  CLIENT_CREATE_LIKE: 'CLIENT_CREATE_LIKE',
  CLIENT_REMOVE_LIKE: 'CLIENT_REMOVE_LIKE',

  CATEGORY_LOADING: 'CATEGORY_LOADING',
  CATEGORY_LIST: 'CATEGORY_LIST',
  CATEGORY_PRODUCTS: 'CATEGORY_PRODUCTS'
};
export default Types;
